### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH with letsencrypt certificates

### ISSUE THREAD

**Issue by pho3nixf1re** [jacobalberty/unifi-docker#70] opened 2017-10-20 22:07 UTC
### Host operating system

Debian GNU/Linux 8

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```yaml
version: '3'
services:
  letsencrypt:
    container_name: letsencrypt
    image: csmith/letsencrypt-lexicon:latest
    restart: always
    environment:
      PROVIDER: 'dnsimple'
      ACCEPT_CA_TERMS: 'true'
    env_file:
      - .env
    volumes:
      - ./data/letsencrypt:/letsencrypt
  unifi:
    container_name: unifi
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi:latest
    network_mode: host
    restart: always
    volumes:
      - ./data/unifi:/unifi
      - ./data/letsencrypt/certs/gateway.feliciterra.com:/unifi/cert
```

### What do you expect to happen?

For the TLS certs to work when visiting with a browser.

### What actually happens?

I've tried a variety of things here but can't seem to get anything to work. The error displayed in chrome is `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` and in Firefox it's `SSL_ERROR_NO_CYPHER_OVERLAP`. If I remove my letsencrypt certificates everything works fine with the self-signed cert. It seems that the letsencrypt certs are broken when imported into unifi. These exact same certs I have mounted in other services and running just fine. I have rebuilt the container numerous times all with the same results.

**Comment by jacobalberty** [comment] 2017-10-20 22:53
I'm using letsencrypt certs myself, though my setup is a hair different. What does docker-compose logs unifi show?

**Comment by pho3nixf1re** [comment] 2017-10-21 00:10
```
[2017-10-20 22:16:56,398] <docker-entrypoint> Cert directory found. Checking Certs
[2017-10-20 22:16:56,408] <docker-entrypoint> Cert has changed, updating controller...
[2017-10-20 22:16:56,410] <docker-entrypoint> Using openssl to prepare certificate...
[2017-10-20 22:16:56,420] <docker-entrypoint> Removing existing certificate from Unifi protected keystore...
keytool error: java.lang.Exception: Keystore file does not exist: /unifi/data/keystore
[2017-10-20 22:16:56,605] <docker-entrypoint> Inserting certificate into Unifi keystore...
[2017-10-20 22:16:57,052] <docker-entrypoint> Importing cert into Unifi database...
parse chain.pem (PEM, 1 certs): CN=Let's Encrypt Authority X3
parse tmp.CAVYf7Ueo2 (PEM, 1 certs): CN=DST Root CA X3
parse cert.pem (PEM, 1 certs): CN=gateway.feliciterra.com
Importing signed cert[gateway.feliciterra.com]
... issued by [CN=Let's Encrypt Authority X3]
... issued by [CN=DST Root CA X3]
Certificates successfuly imported. Please restart the UniFi Controller.
[2017-10-20 22:16:57,688] <docker-entrypoint> Done!
[2017-10-20 22:16:57,693] <docker-entrypoint> Starting unifi controller service.
[2017-10-20 22:16:57,695] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
```

**Comment by jacobalberty** [comment] 2017-10-21 00:24
Ok, I think I know the issue, you can work around this by removing your cert temporarily, delete the /unifi/data/keystore file, then start unifi without the cert or keystore, let unifi create a new keystore by launching it without the cert of keystore file, then add the cert back and remove cert.pem.md5 and restart the unifi container. I'll have to modify import_cert to handle a missing keystore.

Please let me know if this fixes the issue or not.

**Comment by pho3nixf1re** [comment] 2017-10-21 00:52
I noticed that error myself but it didn't seem to actually cause an error. I did what you suggested like with a working self-signed cert:

```
$ docker-compose stop unifi
$ docker-compose rm unifi
$ rm data/letsencrypt/*.md5
$ docker-compose up -d unifi
$ docker logs unifi

[2017-10-21 00:40:21,707] <docker-entrypoint> Cert directory found. Checking Certs
[2017-10-21 00:40:21,719] <docker-entrypoint> Cert has changed, updating controller...
[2017-10-21 00:40:21,721] <docker-entrypoint> Using openssl to prepare certificate...
[2017-10-21 00:40:21,730] <docker-entrypoint> Removing existing certificate from Unifi protected keystore...
[2017-10-21 00:40:21,926] <docker-entrypoint> Inserting certificate into Unifi keystore...
[2017-10-21 00:40:22,356] <docker-entrypoint> Importing cert into Unifi database...
parse chain.pem (PEM, 1 certs): CN=Let's Encrypt Authority X3
parse tmp.4gxOuQjLDp (PEM, 1 certs): CN=DST Root CA X3
parse cert.pem (PEM, 1 certs): CN=gateway.feliciterra.com
Importing signed cert[gateway.feliciterra.com]
... issued by [CN=Let's Encrypt Authority X3]
... issued by [CN=DST Root CA X3]
Certificates successfuly imported. Please restart the UniFi Controller.
[2017-10-21 00:40:22,984] <docker-entrypoint> Done!
[2017-10-21 00:40:22,988] <docker-entrypoint> Starting unifi controller service.
[2017-10-21 00:40:22,989] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode

```

But I still get the cipher error.

**Comment by pho3nixf1re** [comment] 2017-10-21 01:15
If it helps, `curl` is throwing this:

`curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`

**Comment by jacobalberty** [comment] 2017-10-21 01:15
Hmm, anything relevant in /unifi/log/unifi.err.log or /unifi/log/server.log?

**Comment by pho3nixf1re** [comment] 2017-10-21 01:22
There are no errors in the server.log or in any of the others. Everything seems to start up OK. Can you reproduce the issue at all using the above compose file? If you want to assist more I can share my private repo with you since there are no secrets in it.

**Comment by jacobalberty** [comment] 2017-10-21 01:33
The problem I have with completely reproducing your setup is I use he.net for my dns, and lexicon doesn't support my dns provider. The original author of the import_cert script uses the same setup you use though so it should just work.

What do you get for the output of `openssl x509 -in cert.pem -noout -text`

You can leave out the long chain of numbers for modulus and the long chain of numbers after the signature algorithm, but please include the signature algorithm. Your output should look like this

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            04:bf:26:b6:dd:cb:3c:01:52:fe:e1:e3:b0:7f:3c:62:1d:c2
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity
            Not Before: Oct 19 17:41:57 2017 GMT
            Not After : Jan 17 17:41:57 2018 GMT
        Subject: CN = unifi.lan.avsbr.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                20:0F:CC:91:B9:9A:73:17:DC:6B:7E:B5:36:03:49:30:F4:7C:10:C8
            X509v3 Authority Key Identifier:
                keyid:A8:4A:6A:63:04:7D:DD:BA:E6:D1:39:B7:A6:45:65:EF:F3:A8:EC:A1

            Authority Information Access:
                OCSP - URI:http://ocsp.int-x3.letsencrypt.org
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/

            X509v3 Subject Alternative Name:
                DNS:unifi.lan.avsbr.com
            X509v3 Certificate Policies:
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org
                  User Notice:
                    Explicit Text: This Certificate may only be relied upon by Relying Parties and only in accordance with the Certificate Policy found at https://letsencrypt.org/repository/

    Signature Algorithm: sha256WithRSAEncryption
```

If for some reason you see anything about key in the output of that command, do not paste it here you're either reading the wrong file or the other container is misconfigured and putting the wrong file in the wrong location.

**Comment by pho3nixf1re** [comment] 2017-10-21 01:56
Here is my cert info:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:80:3d:42:85:24:99:6b:65:eb:89:7a:95:52:b7:28:bd:e8
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity
            Not Before: Oct 21 00:32:39 2017 GMT
            Not After : Jan 19 00:32:39 2018 GMT
        Subject: CN = gateway.feliciterra.com
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (384 bit)
                ASN1 OID: secp384r1
                NIST CURVE: P-384
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                75:51:B2:A1:22:2F:52:8D:81:96:53:08:40:52:37:44:E3:34:F2:E6
            X509v3 Authority Key Identifier:
                keyid:A8:4A:6A:63:04:7D:DD:BA:E6:D1:39:B7:A6:45:65:EF:F3:A8:EC:A1

            Authority Information Access:
                OCSP - URI:http://ocsp.int-x3.letsencrypt.org
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/

            X509v3 Subject Alternative Name:
                DNS:gateway.feliciterra.com
            X509v3 Certificate Policies:
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org
                  User Notice:
                    Explicit Text: This Certificate may only be relied upon by Relying Parties and only in accordance with the Certificate Policy found at https://letsencrypt.org/repository/

    Signature Algorithm: sha256WithRSAEncryption

```

As a side note, I can reproduce this on other machines using me stock setup so something is definitely up here.

**Comment by pho3nixf1re** [comment] 2017-10-21 01:59
Also, just a reminder that this same cert is being used in other containers just fine.

**Comment by jacobalberty** [comment] 2017-10-21 02:04
In system.properties did you change unifi.https.ciphers or unifi.https.sslEnabledProtocols?

**Comment by pho3nixf1re** [comment] 2017-10-21 02:05
I had done so in earlier attempts to fix this but the logs above are using the defaults with those commented out.

**Comment by jacobalberty** [comment] 2017-10-21 02:29
Ok, I know this is going to sound stupid but its the certificate. Yours says `Public Key Algorithm: id-ecPublicKey`, note mine says `Public Key Algorithm: rsaEncryption`. id-ecPublicKey is an ECC certificate apparently it's on the feature requests https://community.ubnt.com/t5/UniFi-Feature-Requests/UniFi-Controller-does-not-support-ECC-certificates/idi-p/1700108 . I'm checking the forums to see if theres a way to enable ECC Certificates .

Apparently some people have been able to correct the same output error by adding 
`unifi.https.ciphers=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,SSL_RSA_WITH_RC4_128_SHA
`
to system.properties, but I'm not confident that is the correct fix.

**Comment by pho3nixf1re** [comment] 2017-10-21 02:31
I made that cipher change already to no effect. I was unaware of the ECC issue but that definitely sounds like the issue. It's trivial for me to generate a new certificate but I'm using the container `csmith/letsencrypt-lexicon` which I don't believe has a way to customize that. I'll look into how I might change that and report back. Thank you so much for helping me work through this!

**Comment by pho3nixf1re** [comment] 2017-10-21 02:40
That did it! I shut everything using the certs down, deleted the certs, then spun up the `letsencrypt` service to regenerate them with the environment flag `ALGORITHM=rsa`. Brought up unifi and the other containers and now everything is running great. So. Much. Pain.

**Comment by jacobalberty** [comment] 2017-10-21 02:43
Glad we could figure it out, hopefully ubnt gets on the ball and gets ecc support

**Comment by kenperkins** [comment] 2020-04-11 18:06
I found this issue today after getting an ECC certificate from LE, and was able to work around (5.12) without having to use the RSA algorithm for LE.

I had to set these two lines in `system.properties` explicitly:

```
unifi.https.sslEnabledProtocols=TLSv1.2unifi.https.ciphers=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
```

via https://www.c0ffee.net/blog/unifi-cloud-key-ssl-certificate/

**Comment by jacobalberty** [comment] 2020-04-11 18:42
Ok I quickly added it into the beta build which should be building on the hub now, use the environment variable UNIFI_ECC_CERT=true with the current beta tag and it should set those. I'll play with it and see if i run into any issues then make it the default. At that point I'll close this back.

**Comment by hollec** [comment] 2020-04-11 20:40
Did the recent change make the defaults (UNIFI_ECC_CERT not set) to be ECC parameters? I pulled down the latest beta build this afternoon while making some other unrelated tweaks to my docker setup and now have the following settings in my system.properties file:

```
unifi.https.ciphers=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
unifi.https.sslEnabledProtocols=TLSv1.2
```

I don't have ECC certs, so I now get a ERR_SSL_VERSION_OR_CIPHER_MISMATCH error in my browser.

**Comment by jacobalberty** [comment] 2020-04-11 20:43
It's not supposed to be the default i'll fix it shortly.

**Comment by jacobalberty** [comment] 2020-04-11 20:53
@hollec  sorry about that, I had originally intended for it activate if UNIFI_ECC_CERT had any value via checking for ! -Z but changed it to be true, and left the ! there when I changed the behavior. It's building on the hub now. I Was hoping the changes wouldnt break RSA certs. I'll have to set the ciphers correctly to work with RSA certs before merging

**Comment by hollec** [comment] 2020-04-11 21:26
No worries! I cleaned up my system.properties file after the updated image finished building and I'm back up and running.

**Comment by danielbotting-mcr** [comment] 2021-11-04 14:27
Hi,
We are having the same problem,

Version: 6.2.25

In an initial attempt to resolve I stopped the container, removed it, deleted the image and pulled, our version is now 6.4.54, the issues persists.

I have checked the docker- entrypoint.sh and it reflects the changes in:

https://github.com/jacobalberty/unifi-docker/commit/0dd21cb8820a80afd86bb32c2a5e858873927ecc

Our public key Alogorithim is:

Public Key Algorithm: id-ecPublicKey

We've not specifically set the variable UNIFI_ECC_CERT, should we?

In server.log it advises the version update, checking the docker log in version 6.2.25:

[2021-10-27 18:30:30,566] <docker-entrypoint> Cert directory found. Checking Certs
[2021-10-27 18:30:30,594] <docker-entrypoint> Cert has changed, updating controller...
[2021-10-27 18:30:30,598] <docker-entrypoint> Using openssl to prepare certificate...
[2021-10-27 18:30:30,622] <docker-entrypoint> Removing existing certificate from Unifi protected keystore...
[2021-10-27 18:30:30,926] <docker-entrypoint> Inserting certificate into Unifi keystore...
Importing keystore /tmp/tmp.8ctWlXG4Pe to /unifi/data/keystore...

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /unifi/data/keystore -destkeystore /unifi/data/keystore -deststoretype pkcs12".

I'm presuming this was resolved by the container update as it no longer appears:

2021-11-04 11:10:02,849] <docker-entrypoint> Cert directory found. Checking Certs
[2021-11-04 11:10:02,855] <docker-entrypoint> Cert has not changed, not updating controller.
[2021-11-04 11:10:02,863] <docker-entrypoint> Starting unifi controller service.
[2021-11-04 11:10:02,925] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode

Thanks

Daniel

**Comment by thinkl33t** [comment] 2021-11-08 12:25
I can confirm that setting this variable allowed the ECC certificate to work.

@jacobalberty would it be worth detecting the type of certificate being presented and setting / unsetting this flag automatically in future?

**Closed** 2022-02-23 02:20 UTC
Labels: no-issue-activity

**Comment by jadsy2107** [comment] 2022-06-20 04:22
I'm having same issue on Debian 9

**Comment by liyanage** [comment] 2023-03-03 09:15
Just wanted to quickly comment that even now in 2023 this is definitely still an issue.

Setting UNIFI_ECC_CERT=true made this work for me with a Let's Encrypt certificate. Indeed my cert uses the affected key algorithm noted above:

```
 % openssl x509 -text < certbot-config/live/vera-and-marc.com/cert.pem | grep 'Public Key Algorithm'
            Public Key Algorithm: id-ecPublicKey
```

It was pretty hard to find this key bit of information, It think it would be helpful to add it to the [Certificate Support](https://github.com/jacobalberty/unifi-docker#certificate-support) section of the README.

I just created this PR to do that: https://github.com/jacobalberty/unifi-docker/pull/645.

**Comment by 82280zx** [comment] 2023-04-25 18:48
> 

I agree with this I had do do allot of digging to find this adding UNIFI_ECC_CERT=true also fixed my lets encrypt cert issues I was having. Updating the Certificate Support section would save a lot of people some grief, thank you for making this docker image it saves allot of time and headache!
