### ISSUE TITLE
QNAP TS-451 locks up when trying to install

### ISSUE THREAD

**Issue by Tomnibus** [jacobalberty/unifi-docker#23] opened 2017-01-27 17:01 UTC
My problem is installing this causes my QNAP to lock up. I have a TS-451 QNAP. 

I installed the Container Station so that was fine (took a bit but it worked) Then first I simply searched for the unifi and installed it that way based on another video and it locked up at 83% complete and my system was inaccessible. I needed to force a reboot, uninstall container station and do a media check of the drives.

I saw a video from the docker comments and decided to try installing it via SSH. The command I ran was:

docker run --name unifi-uap-controller --net=host -d jacobalberty/unifi:latest

It downloaded everything but it locked up while extracting the 200MB file and so I thought perhaps it was simply "stuck" so I went to bed and looked at it this morning. In the morning it was still inaccessible so I had to force a reboot again. This time I had to check the volume but at least Container station sort of loaded. I say sort of because it sat for 40 minutes on "loading" whereas before it gave a big red "can't load" error.

I ended up uninstalling it again and just putting my port back to 8080 and I'm deciding that my QNAP cannot handle this unless someone reading this knows what else I can do to get it installed.

Incidentally I have over 2TB of space available on the volume so it's not full.

**Comment by jacobalberty** [comment] 2017-01-27 17:08
I'm not familiar with QNAP enough to help, hopefully someone who uses QNAP will chime in, but have you posted on the QNAP community forums as well? (https://forum.qnap.com/)

**Comment by Tomnibus** [comment] 2017-01-27 17:17
I have not, but thanks for pointing me in that direction. I will see what they say.

**Comment by jacobalberty** [comment] 2017-02-01 19:37
just wanted to follow up did you manage to find a fix for this?

**Comment by Tomnibus** [comment] 2017-02-01 20:08
No, never, I bought a $78 Unifi CloudKey unfortunately.

**Comment by ahiguero** [comment] 2017-02-02 16:58
i can confirm that the issue is still happening on a TS-453A with 8 GBs of ram and plenty of space. this was not happening before on your older images.

**Comment by jacobalberty** [comment] 2017-02-02 17:37
@ahiguero I believe QNAP had issues in the past they had to push a firmware upgrade for, do other docker images work presently on your qnap system?

**Comment by ahiguero** [comment] 2017-02-02 17:39
i tried yours before and it was working i believe 5.2.9 the latest imaged definitely did something to nas that required me to reboot it. my nass is running the latest firmware and yes i do have other images running. i will give it another try

**Comment by jacobalberty** [comment] 2017-02-02 18:05
Theres only two significant changes in that latest image, one was the switch to jdk-8 and the other was using dumb-init instead of launching java directly. but from his description it's locking up when extracting, so nothing from the image is running yet its just extracting data from it.

**Comment by ahiguero** [comment] 2017-02-02 18:40
thanks for the reply jacob. the issue that i have happens when i try to create and run the container the first time.

**Comment by raidancampbell** [comment] 2017-02-03 00:40
TVS871/i7/16gb/QTS4.2.3/Container station 1.6.1709

I've never used any of this unifi stuff before and I have no idea what I'm supposed to be looking for, but @jacobalberty was looking for another qnap user to test this.  Additionally I have effectively zero experience with docker or the container station.  To test this, I did the following:

container station -> create container -> search `jacobalberty` -> `create` `jacobalberty/unifi` -> `Command` *empty* -> `Entrypoint` *empty* -> `CPU limit` 50% -> `Memory Limit` 4096MB.

The container was created successfully, and `ps auxww` has the following:

```
root@34898f1c1b55:/usr/lib/unifi/data# ps auxww                                                                                                                                               
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND                                                                                                                      
root         1  0.0  0.0    192     4 ?        Ss   Feb02   0:00 /usr/bin/dumb-init -- /usr/local/bin/unifi.sh                                                                                
root         6  0.0  0.0   4328   636 ?        Ss+  Feb02   0:00 sh /usr/local/bin/unifi.sh                                                                                                   
root         8  0.0  0.0   8488   664 ?        S+   Feb02   0:00 unifi -nodetach -home /usr/lib/jvm/java-8-openjdk-amd64 -classpath /usr/share/java/commons-daemon.jar:/usr/lib/unifi/lib/ace.
jar -pidfile /var/run/unifi/unifi.pid -procname unifi -outfile /var/log/unifi/unifi.out.log -errfile /var/log/unifi/unifi.err.log -Dunifi.datadir=/var/lib/unifi -Dunifi.rundir=/var/run/unifi
 -Dunifi.logdir=/var/log/unifi -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xmx1024M com.ubnt.ace.Launcher start                                                                           
root         9  0.1  0.3 3884668 55968 ?       Sl+  Feb02   0:00 unifi -nodetach -home /usr/lib/jvm/java-8-openjdk-amd64 -classpath /usr/share/java/commons-daemon.jar:/usr/lib/unifi/lib/ace.
jar -pidfile /var/run/unifi/unifi.pid -procname unifi -outfile /var/log/unifi/unifi.out.log -errfile /var/log/unifi/unifi.err.log -Dunifi.datadir=/var/lib/unifi -Dunifi.rundir=/var/run/unifi
 -Dunifi.logdir=/var/log/unifi -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xmx1024M com.ubnt.ace.Launcher start                                                                           
root        30  0.8  1.1 6768820 187800 ?      Sl+  Feb02   0:06 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx1024M -XX:ErrorFile=/usr/lib/unifi/data/logs/hs_err_pid<pid>.log -Dapple.a
wt.UIElement=true -jar /usr/lib/unifi/lib/ace.jar start                                                                                                                                       
root        57  0.3  0.3 1272144 49568 ?       Sl+  Feb02   0:03 bin/mongod --dbpath /usr/lib/unifi/data/db --port 27117 --logappend --logpath logs/mongod.log --nohttpinterface --bind_ip 127
.0.0.1                                                                                                                                                                                        
root       112  0.0  0.0  20236  1980 ?        Ss+  Feb02   0:00 /bin/bash                                                                                                                    
root       128  0.0  0.0  20236  1984 ?        Ss   00:11   0:00 /bin/bash                                                                                                                    
root       134  0.0  0.0  17492  1136 ?        R+   00:12   0:00 ps auxww   
```
or, as shown in the readme, the output of `ps -e -o pid,ppid,cmd | more`:
```
root@34898f1c1b55:/usr/lib/unifi/data# ps -e -o pid,ppid,cmd | more                                                                                                                           
  PID  PPID CMD                                                                                                                                                                               
    1     0 /usr/bin/dumb-init -- /usr/local/bin/unifi.sh                                                                                                                                     
    6     1 sh /usr/local/bin/unifi.sh                                                                                                                                                        
    8     6 unifi -nodetach -home /usr/lib/jvm/java-8-openjdk-amd64 -classpath /usr/share/java/commons-daemon.jar:/usr/lib/unifi/lib/ace.jar -pidfile /var/run/unifi/unifi.pid -procname unifi
 -outfile /var/log/unifi/unifi.out.log -errfile /var/log/unifi/unifi.err.log -Dunifi.datadir=/var/lib/unifi -Dunifi.rundir=/var/run/unifi -Dunifi.logdir=/var/log/unifi -Djava.awt.headless=tr
ue -Dfile.encoding=UTF-8 -Xmx1024M com.ubnt.ace.Launcher start                                                                                                                                
    9     8 unifi -nodetach -home /usr/lib/jvm/java-8-openjdk-amd64 -classpath /usr/share/java/commons-daemon.jar:/usr/lib/unifi/lib/ace.jar -pidfile /var/run/unifi/unifi.pid -procname unifi
 -outfile /var/log/unifi/unifi.out.log -errfile /var/log/unifi/unifi.err.log -Dunifi.datadir=/var/lib/unifi -Dunifi.rundir=/var/run/unifi -Dunifi.logdir=/var/log/unifi -Djava.awt.headless=tr
ue -Dfile.encoding=UTF-8 -Xmx1024M com.ubnt.ace.Launcher start                                                                                                                                
   30     9 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx1024M -XX:ErrorFile=/usr/lib/unifi/data/logs/hs_err_pid<pid>.log -Dapple.awt.UIElement=true -jar /usr/lib/unifi/lib/ace.jar sta
rt                                                                                                                                                                                            
   57    30 bin/mongod --dbpath /usr/lib/unifi/data/db --port 27117 --logappend --logpath logs/mongod.log --nohttpinterface --bind_ip 127.0.0.1                                               
  112     0 /bin/bash                                                                                                                                                                         
  128     0 /bin/bash                                                                                                                                                                         
  144     0 /bin/bash                                                                                                                                                                         
  154   144 ps -e -o pid,ppid,cmd                                                                                                                                                             
  155   144 more 
```
Here is an image of the container station running:
<img width="1026" alt="screenshot 2017-02-02 19 13 25" src="https://cloud.githubusercontent.com/assets/5506073/22574236/bc0f3412-e97b-11e6-99dd-3a4f65cbb2a6.png">

I'm assuming I had exactly zero issues with this.

The network access, however, isn't perfect.  
- `http://tombstone:32771/`, which maps to the container's port 8080, automatically redirects to port 8443/manage/wizard/ for HTTPS.  This is not mapped in the container, and since the host has no server running on it, the connection is rejected.
- `http://tombstone:32768/`, which maps to the container's port 3478[UDP] yields an Apache Tomcat error 400 (The request sent by the client was syntactically incorrect.).

The `port forwarding` section was automatically configured as follows:
<img width="661" alt="screenshot 2017-02-02 19 31 22" src="https://cloud.githubusercontent.com/assets/5506073/22574669/470bd26c-e97e-11e6-83b1-4459735f90a8.png">

Using this, I tried accessing `https://tombstone:32770/manage/wizard/`, and successfully saw a `UniFi Setup Wizard` landing page.

**Comment by ahiguero** [comment] 2017-02-03 00:45
raidan with this setup can you then discover your devices? for me i set it up using bridge mode and it worked fine.

**Comment by raidancampbell** [comment] 2017-02-03 00:48
I don't have any ubiquiti gear, I just came here to test whether the image would lock up during installation

**Comment by jacobalberty** [comment] 2017-02-04 21:56
5.4.9 got pulled by ubnt, semes there were issues, im curious if 5.3.11 works, the :latest and :5.3.11 tags are both 5.3.11 but they use different base images at the moment, im curious if one or both work for y'all.

**Comment by ajdexter** [comment] 2017-03-11 21:57
Running a QNAP TS-563.  with :latest and also :5.3.11 work for me as normal. I've not had any lockups as a result of the last 10 or so tags. At least not for my machine.

**Closed** 2017-06-26 17:05 UTC
