### ISSUE TITLE
Multi-arch image support

### ISSUE THREAD

**Issue by Jukie** [jacobalberty/unifi-docker#360] opened 2020-10-14 05:14 UTC
I'd like to contribute to this project by adding multi-arch build support instead of individual arch tagged images. I run a mixed arch homelab cluster and having the ability to run this on any node would be great.

What's the current process you take to build/push images to DockerHub? All of the recent builds have failed through TravisCI and I didn't see a push happening anywhere there so I was having trouble finding this piece.

Would you be open to me implementing something like https://www.docker.com/blog/multi-arch-build-what-about-travis/?

**Comment by jacobalberty** [comment] 2020-10-14 14:56
> What's the current process you take to build/push images to DockerHub? 

I am building on the docker hub itself using the automated builds or whatever they're calling it this week.

>  All of the recent builds have failed through TravisCI 

Yeah the Travis builds broke a bit ago, IIRC the unifi webserver started taking longer to bring come up and I couldn't decide on a reliable way of determining a working build so I just hadn't fixed it.

>  sleep 10 && curl -kILs --fail https://127.0.0.1:8443 || exit 1
> curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.

Shouldn't be too hard to fix, easiest options are just increase the sleep before hand and continue using that command,  or drop the curl altogether and rely on ps and logs as indications of a working build


> Would you be open to me implementing something like https://www.docker.com/blog/multi-arch-build-what-about-travis/?

Using travis would be the easiest route by far

**Comment by Jukie** [comment] 2020-10-14 16:22
Alright great, I'll test changes in my own hub to avoid any issues as well but will have a PR ready soon.

**Comment by jacobalberty** [comment] 2020-10-14 16:30
I have one big question on the docker blog post,  what happens with pull requests? If I follow that exact setup it looks like any pull request will attempt to overwrite the image on the docker hub with the pull request.

I believe we should use $TRAVIS_BRANCH for the  tag name as well, that way rc and beta can continue to function,

**Comment by Jukie** [comment] 2020-10-14 16:53
Agreed I wouldn't follow that, I think branch tags make the most sense and when a PR comes in it should only overwrite that branch tag. 

Maybe you could configure the latest tag in hub to track master just retag that image somewhere?
I have limited Travis experience but I imagine it supports building based on git release tags too so that should continue to function as well.

**Comment by jacobalberty** [comment] 2020-10-14 17:00
$TRAVIS_BRANCH seems to be the variable to use to build based on git tags/branches but it appears to contain even the target branch I'm looking into it now to figure out the best way to handle it

**Comment by jacobalberty** [comment] 2020-10-14 18:54
Ok so the docker hub guide seems to be missing a step https://medium.com/@quentin.mcgaw/cross-architecture-docker-builds-with-travis-ci-arm-s390x-etc-8f754e20aaef covers what it was missing
I needed to add qemu-user-static to the apt install line (may even be able to skip this step but I didn't test yet and elsewhere i saw posts saying its needed) and use `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes` before the buildx create line

**Comment by jacobalberty** [comment] 2020-10-14 19:03
The next issue I found is gosu crashes under qemu's arm emulation. It should be safe to just remove 
`
# verify that the binary works
    && gosu nobody true \
` 
from the Dockerfile. That's how I handled it for the arm cross build stuff. I'm also opening a new issue regarding removing gosu entirely and will be deprecating the features that require gosu shortly followed by complete removal.

**Comment by Jukie** [comment] 2020-10-14 21:42
Alright I've got something that builds but I also need to overcome the build log size in travis. See https://travis-ci.org/github/Jukie/unifi-docker/builds/735860281

I'm looking for ways to remove the progress status from the output or remove non-essential logging. I'll let you know if I figure it out.

**Comment by jacobalberty** [comment] 2020-10-14 22:11
use --progress plain in the build comman

**Comment by Jukie** [comment] 2020-10-14 22:12
Yup I’m there already, thanks! Still working through some issues but almost there.

**Comment by jacobalberty** [comment] 2020-10-14 22:24
I think the big issue is going to be arm v7 support, mongo db doesn't have official packages for armv7 and nothing newer than ubuntu 16.04 includes mongodb on armv7

**Comment by jacobalberty** [comment] 2020-10-14 23:21
So here's what I'm thinking. I need to modify the build script and remove all mongo db stuff.

Then have the build script execute anything under say pre-build/<arch> when its done installing pre-requisites but hasn't installed the unifi package, On platforms like arm64 and amd64 mongodb will install on its own through the distrobutions apt repo, then on armhf (armv7) We can either install a dummy mongodb package and just let users install their own mongodb service in another container ala the included docker-compose.yml, or add a complete build script there for mongodb.

**Comment by Jukie** [comment] 2020-10-14 23:51
That's exactly what I was attempting to solve.
Although my setup already uses an external mongo and it wouldn't affect me, I think dropping support for it altogether or only for specific architectures could create problems for users so I'd personally push for adding a mongo build script that works in armhf/armv7 alongside your pre-build/ idea.

**Comment by Jukie** [comment] 2020-10-15 00:14
Alternatively, you could run everything on 16.04 which is still supported through next April. Targeting all platforms while on the arm32v7 branch with buildx succeeds - albeit the temporary removal of `gosu nobody true`.

**Comment by jacobalberty** [comment] 2020-10-15 01:06
is mongodb version 3.6 on 16.04?

**Comment by jacobalberty** [comment] 2020-10-15 01:18
I just checked it looks like [mongodb on 16.04](https://packages.ubuntu.com/xenial/database/mongodb) is 2.6 the version regression could break existing installs. 

another option is not include arm32v7 for now while testing and don't bring it out to the master until I get a working build script for mongodb on 18.04 (or maybe 20.04), my only concern there would be time limits on travis-ci building a whole mongodb package

**Comment by jacobalberty** [comment] 2020-10-15 01:20
https://github.com/ddcc/mongodb/releases This has mongodb 3.2 prebuilt for armhf, which is better than nothing, the armhf build script could just pull and install that while other architectures use the distro included ones.

**Comment by Jukie** [comment] 2020-10-15 01:27
Yeah that could work. I assumed it was there based on https://github.com/jacobalberty/unifi-docker/blob/arm32v7/docker-build.sh#L40 but you're correct that 2.6 is what actually is being installed on the arm32v7 image right now.

**Comment by jacobalberty** [comment] 2020-10-15 01:41
Ok prebuild system has been added into beta. It can be pulled into your tree by doing a `git pull` then `git cherry-pick 290029d7557ace802e0bf5841c984e742ad9a11b`. I will start testing to get a  script for pulling 3.2 into armhf

**Comment by jacobalberty** [comment] 2020-10-15 02:13
If you put the following in pre_build/armhf/mongodb.sh this should allow armv7 to build:

```bash
#!/usr/bin/env bash
VER=3.2.22-2

TMP=$(mktemp -d)

curl -sL "https://github.com/ddcc/mongodb/releases/download/v${VER}/mongodb_${VER}_armhf.deb" -o "${TMP}/mongodb_${VER}_armhf.deb"
curl -sL "https://github.com/ddcc/mongodb/releases/download/v${VER}/mongodb-server_${VER}_all.deb" -o "${TMP}/mongodb-server_${VER}_all.deb"
for f in clients server-core; do
  pn="mongodb-${f}_${VER}_armhf.deb"
  curl -sL "https://github.com/ddcc/mongodb/releases/download/v${VER}/${pn}" -o "${TMP}/${pn}"
done

apt -qy install "$TMP/"*
rm -rf "$TMP"
```

I have not tested it in docker yet just on a host system and it appeared to work fine.

**Comment by jacobalberty** [comment] 2020-10-16 17:20
I have a test `multiarch` image up now, the code isn't checked into the repository yet as I still have some logistical hub issues to work out.

**Comment by Jukie** [comment] 2020-10-16 17:24
Okay great, I don’t think we’ll ever get +3.2 running on armed/arm32v7 due to underlying dependencies.

**Comment by jacobalberty** [comment] 2020-10-16 17:42
Yeah I fear armhf support needs to be deprecated in the long run. But if I can I'd like to get at least 3.2 running on 20.04. I'll likely have to work out building 3.2 packages myself. Should be able to do it with just github actions though. [this post](https://www.dcddcc.com/blog/2018-06-09-building-mongodb-for-32-bit-ARM-on-debian-ubuntu.html) seems to contain all of the instructions I need to do it and links to a fork of mongo 3.2 with the work done, just need to set up a build environment for it.

**Comment by jacobalberty** [comment] 2020-10-16 20:10
And the `multiarch` tag is live on the docker hub as well as checked into github.

I'm thinking when I go to move `latest` from `stable-5` to `stable-6` that should be a good time to merge this into `latest` as well. if 6.0.28 makes it out of beta and then rc without issue I'm hoping to move `latest` with 6.0.28.

**Comment by elfhack** [comment] 2020-10-17 15:49
@jacobalberty Not to rush or anything, but this is the only image that for now works on my odroid C4 (S905X3 chip), all the other ones crash on mongo with a bus error. 6.0.23 isn't my version of choice, I'd love to stay on 5.14, but if I'm to go with 6.0, I'd love to have the freshest stable

**Comment by jacobalberty** [comment] 2020-10-17 16:28
@elfhack on the freshest stable the consensus on community.ubnt.com seems to be that what is on https://www.ui.com/download/unifi/ is the latest stable the ones newer on the community downloads are rc, so i'm going with that for now. If you'd like to use 5.14 with the multiarch images I just built a `multiarch-5` tag you can try out with 5.14.23 in it

**Comment by elfhack** [comment] 2020-10-17 18:37
> @elfhack on the freshest stable the consensus on community.ubnt.com seems to be that what is on https://www.ui.com/download/unifi/ is the latest stable the ones newer on the community downloads are rc, so i'm going with that for now. If you'd like to use 5.14 with the multiarch images I just built a `multiarch-5` tag you can try out with 5.14.23 in it

Thanks for the quick response, it works wondefully now!

**Comment by jacobalberty** [comment] 2020-10-19 19:30
I have now pushed these changes into `beta` and `rc` as well, fingers crossed that 6.0.28 makes it onto the main [download page](https://www.ui.com/download/unifi/) soon without issue the 6.0.28-rc tag is built against the new multiarch stuff so as of this comment I'm officially dogfooding this instead of just testing builds out in isolation.

#323  may still be an issue, Hoping to get someone else to chime in on it. If it is I think I know the fix (and the multiarch stuff makes the fix easy now) but I don't want to throw random fixes in without confirming it's still an issue.

**Comment by Jukie** [comment] 2020-10-19 20:31
Awesome, thanks for the quick implementation here!

**Comment by Jukie** [comment] 2020-10-19 20:33
From the PR:
> This should fully implement multi-arch images via travis-ci, all that is left is to ensure armhf (arm32v7) works properly

Does that mean you're waiting for an armhf user to validate? I can attest to the both the rc and 6.0.23-ma images running successfully in my environment on armhf.

**Comment by jacobalberty** [comment] 2020-10-19 20:52
@Jukie that is indeed what I mean. Good to know then

**Comment by Jukie** [comment] 2020-10-19 20:55
I did see #323 and at least wanted to clarify that I have a pretty simple setup and haven’t tried anything with remote access though.

**Comment by jacobalberty** [comment] 2020-10-19 21:25
Ok I figured up my raspberry pi and confirmed it works with `multiarch`

**Closed** 2020-10-20 14:55 UTC
